server.port=${PORT:8080}
spring.application.name=optica
# CONEXIÓN BASE DE DATOS RENDER
#  spring.datasource.url=jdbc:postgresql://dpg-d7hqunnaqgkc739gnccg-a.virginia-postgres.render.com/opticaw_bd?sslmode=require
# spring.datasource.username=opticaw_bd_user
# spring.datasource.password=djuyRyhY8aiBdsYdAvkwpV9tSfy1FZlE

# CONEXIÓN BASE DE DATOS RAILWAY
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:opticaw_bd}${SSL_MODE:}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:12345}

# CONFIGURACIÓN BASE DE DATOS LOCAL
# spring.datasource.url=jdbc:postgresql://localhost:5432/opticaBD
# spring.datasource.username=postgres
# spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql:true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.type.descriptor.sql.BasicBinder.level=TRACE

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
media.location=mediafiles

# ✅ CONFIGURACIÓN BREVO (PARA ENVIAR CORREOS VÍA API HTTP)
brevo.api.key=${SENDINBLUE_API_KEY}

# ✅ CONFIGURACIÓN DEL FRONTEND (NETLIFY EN PRODUCCIÓN, LOCALHOST EN DESARROLLO)
app.frontend.url=https://nissivision.netlify.app/