spring.application.name=optica
spring.datasource.url=jdbc:postgresql://localhost:5432/opticaBD
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql:true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.type.descriptor.sql.BasicBinder.level=TRACE

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
media.location=mediafiles

# ✅ CONFIGURACIÓN GMAIL (PARA ENVIAR CORREOS)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rhmjclaro95@gmail.com
# AQUÍ PEGA EL CÓDIGO DE 16 LETRAS QUE OBTENGAS EN GOOGLE
spring.mail.password=mwdb qmsz omri lmda
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true